# simple gh-actions workflow to download magnet links
# and seed for the rest of the execution run (up to 6 hours)
# note: gh-actions limits file sizes to 5GB

name: aria2
on: push

jobs:
  Download:
    runs-on: ubuntu-latest
    env:
      MAGNET: "magnet:?xt=urn:btih:485c153663095a0660c4fae134ae2e019a9ba9e0&dn=%5BBlurayDesuYo%5D%20Kobayashi-san%20Chi%20no%20Maid%20Dragon%20S%20-%2013%20OVA%20%28BD%201920x1080%2010bit%20AAC%29%20%5BD93B9111%5D.mkv&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce"
    steps:
      - name: Download file(s)
        run: |
          mkdir dl
          aria2c -d dl --seed-time=0 "$MAGNET"
      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dl
          retention-days: 1
      - name: Seed file(s) as long as possible
        run: aria2c -V --seed-ratio=0 -d dl "$MAGNET"
