# barebones gh-actions workflow to download magnet links as a build artifact
# and seed for the rest of the execution run (probably 6 hours)
# soft limit on disk space per job is 25GB, artifact is zipped on the same runner
# use SSH server if download is over 12GB
name: Download Magnet by Proxy
on: push

jobs:
  Download:
    runs-on: ubuntu-latest
    env:
      MAGNET: "magnet:?xt=urn:btih:b81ec3750ce9e4ea62c4e9bfb9efb90e1b5c39ba&dn=%5BSubsPlease%5D%20Kobayashi-san%20Chi%20no%20Maid%20Dragon%20S2%20%2801-12%29%20%281080p%29%20%5BBatch%5D&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce"
    steps:
      - name: Download file(s)
        run: |
          mkdir dl parts
          aria2c -d dl --seed-time=0 "$MAGNET"
      - name: Tarball file(s) in place
        run: tar --remove-files -c dl/ | gzip | split -db 1000M - parts/file.tar.gz.
      - name: Upload tarball chunk(s) to litterbox.catbox.moe
        run: |
          for f in parts/*; do
            curl -F 'reqtype=fileupload' -F 'time=24h' -F "fileToUpload=@$f" \
              'https://litterbox.catbox.moe/resources/internals/api.php'
            printf '\n'
          done | tee /dev/stderr > download.txt
      - name: Upload file URL list as artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: download.txt
          retention-days: 30
